name: Container Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Azure Resources
  RESOURCE_GROUP: bench-assignment-2-rg
  REGISTRY_NAME: benchassignment2acr
  BACKEND_APP: bench-assignment-2-api
  FRONTEND_APP: bench-assignment-2-web
  
  # Image Names
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create ACR if not exists
      - name: Create ACR
        run: |
          az acr create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.REGISTRY_NAME }} \
            --sku Basic \
            --admin-enabled true \
            --only-show-errors

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Web/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:latest
          build-args: |
            ConnectionStrings__DefaultConnection=Server=tcp:bench-assignment-2-sql.database.windows.net;Database=bench-assignment-2-db;
            AllowedOrigins__0=https://bench-assignment-2-web.azurewebsites.net

      # Update Backend App Service
      - name: Configure Backend Container
        run: |
          az webapp config container set \
            --name ${{ env.BACKEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.REGISTRY_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
            --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    steps:
      - uses: actions/checkout@v3

      # Build and Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://bench-assignment-2-api.azurewebsites.net

      # Update Frontend App Service
      - name: Configure Frontend Container
        run: |
          az webapp config container set \
            --name ${{ env.FRONTEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.REGISTRY_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
            --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}