name: Build container images for pr

on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    env:
      dotnet-version: 7.0.x
      working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - run: dotnet restore
        working-directory: ${{ env.working-directory }}

      - run: dotnet build --no-restore -p NSwag=true
        working-directory: ${{ env.working-directory }}

      - run: git diff --exit-code

      - run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.working-directory }}

  acr-build-backend:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    steps:
      - name: ACR build backend image
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.Azure_Service_Principal }}
          service_principal_password: ${{ secrets.Azure_Service_Principal_Password }}
          tenant: ${{ secrets.Azure_Tenant }}
          registry: ${{ secrets.Azure_ACR_Registry }}
          repository: pr-${{ github.event.pull_request.number }}
          image: be
          git_access_token: ${{ secrets.ITM_CPH_INTERNAL_GITOPS_READONLY_TOKEN }}
          folder: ./backend
          dockerfile: ./Web/Dockerfile
          branch: ${{ github.head_ref }}
          tag: ${{ github.event.pull_request.head.sha || github.sha }}

  build-and-test-frontend:
    runs-on: ubuntu-latest
    env:
      node-version: 18.x
      working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.node-version }}

      - run: npm ci
        working-directory: ${{ env.working-directory }}
        
      - run: npm run build
        working-directory: ${{ env.working-directory }}
      # - run: npm run test:headless
      #   working-directory: ${{ env.working-directory }}
      
  acr-build-frontend:
    needs: build-and-test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: ACR build frontend image
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.Azure_Service_Principal }}
          service_principal_password: ${{ secrets.Azure_Service_Principal_Password }}
          tenant: ${{ secrets.Azure_Tenant }}
          registry: ${{ secrets.Azure_ACR_Registry }}
          repository: pr-${{ github.event.pull_request.number }}
          image: fe
          git_access_token: ${{ secrets.ITM_CPH_INTERNAL_GITOPS_READONLY_TOKEN }}
          folder: ./frontend
          dockerfile: ./Dockerfile
          branch: ${{ github.head_ref }}
          tag: ${{ github.event.pull_request.head.sha || github.sha }}
