name: Build and run tests backend

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - backend/**
    branches:
      - feature/**

jobs:
  crlf-check:
    name: Check CRLF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1.2.0
        with:
          path: ./backend

  build-and-test-backend:
    runs-on: ubuntu-latest
    env:
      dotnet-version: 7.0.x
      working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - run: dotnet restore
        working-directory: ${{ env.working-directory }}

      - run: dotnet build --no-restore -p NSwag=true
        working-directory: ${{ env.working-directory }}

      - run: git diff --exit-code

      - run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.working-directory }}
